from django.conf import settings as django_settings


EMAIL_ADMIN_NOTIFICATION_RECIPIENTS = getattr(
    django_settings,
    'FACULTY_STORAGE_ALLOCATIONS_EMAIL_ADMIN_NOTIFICATION_RECIPIENTS',
    {})

ELIGIBLE_PI_EMAIL_WHITELIST_ENABLED = getattr(
    django_settings, 'FACULTY_STORAGE_ALLOCATIONS_ELIGIBLE_PI_EMAIL_WHITELIST_ENABLED',
    False)
ELIGIBLE_PI_EMAIL_WHITELIST = getattr(
    django_settings, 'FACULTY_STORAGE_ALLOCATIONS_ELIGIBLE_PI_EMAIL_WHITELIST', [])
