# Generated by Django 5.2.4 on 2025-12-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_storage_allocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalfacultystorageallocationrequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Faculty Storage Allocation Request', 'verbose_name_plural': 'historical Faculty Storage Allocation Requests'},
        ),
        migrations.AlterField(
            model_name='historicalfacultystorageallocationrequest',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
