################################################################################
# pytest
################################################################################

[tool.pytest.ini_options]
addopts = "--continue-on-collection-errors"
markers = [
    "unit: Marks tests as unit tests",
]
python_files = ["test*.py"]
testpaths = [
    # TODO: To add unit tests to an app, create the `unit` directory under
    #  `tests`, and then add the path to it here.
    "coldfront/plugins/hardware_procurements/tests/unit/",
]
# pytest-django
DJANGO_SETTINGS_MODULE = "coldfront.config.settings"
