# Generated by Django 3.2.5 on 2025-10-27 17:23

import coldfront.plugins.cluster_storage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0023_project_allocation_request_mou_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyStorageAllocationRequestStatusChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFacultyStorageAllocationRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('requested_amount_gb', models.PositiveIntegerField()),
                ('approved_amount_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('request_time', models.DateTimeField(blank=True, editable=False)),
                ('approval_time', models.DateTimeField(blank=True, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.JSONField(default=coldfront.plugins.cluster_storage.models.faculty_storage_allocation_request_state_schema)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.project')),
                ('requester', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cluster_storage.facultystorageallocationrequeststatuschoice')),
            ],
            options={
                'verbose_name': 'historical Faculty Storage Allocation Request',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FacultyStorageAllocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('requested_amount_gb', models.PositiveIntegerField()),
                ('approved_amount_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('approval_time', models.DateTimeField(blank=True, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.JSONField(default=coldfront.plugins.cluster_storage.models.faculty_storage_allocation_request_state_schema)),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_scratch_storage_pi', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_scratch_storage_requester', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cluster_storage.facultystorageallocationrequeststatuschoice')),
            ],
            options={
                'verbose_name': 'Faculty Storage Allocation Request',
                'verbose_name_plural': 'Faculty Storage Allocation Requests',
                'permissions': [('can_view_all_storage_requests', 'Can view all storage requests'), ('can_manage_storage_requests', 'Can manage storage requests')],
            },
        ),
    ]
