# Generated by Django 3.2.5 on 2025-10-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultystorageallocationrequest',
            options={'permissions': [('can_view_all_storage_requests', 'Can view all storage requests'), ('can_manage_storage_requests', 'Can manage storage requests')], 'verbose_name': 'Faculty Storage Allocation Request', 'verbose_name_plural': 'Faculty Storage Allocation Requests'},
        ),
    ]
