# Generated by Django 3.2.5 on 2023-05-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_project_allocation_request_billing_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='files')),
            ],
        ),
    ]
