# Generated by Django 3.2.5 on 2023-01-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_project_allocation_request_billing_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproject',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project', 'verbose_name_plural': 'historical projects'},
        ),
        migrations.AlterModelOptions(
            name='historicalprojectreview',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project review', 'verbose_name_plural': 'historical project reviews'},
        ),
        migrations.AlterModelOptions(
            name='historicalprojectuser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project user', 'verbose_name_plural': 'historical Project User Status'},
        ),
        migrations.AlterModelOptions(
            name='historicalsavioprojectallocationrequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Savio Project Allocation Request', 'verbose_name_plural': 'historical Savio Project Allocation Requests'},
        ),
        migrations.AlterModelOptions(
            name='historicalvectorprojectallocationrequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Vector Project Allocation Request', 'verbose_name_plural': 'historical Vector Project Allocation Requests'},
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprojectreview',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprojectuser',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsavioprojectallocationrequest',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvectorprojectallocationrequest',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
