# Generated by Django 3.2.5 on 2023-12-13 20:58

import coldfront.core.utils.mou
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_project_allocation_request_billing_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsavioprojectallocationrequest',
            name='mou_file',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savioprojectallocationrequest',
            name='mou_file',
            field=coldfront.core.utils.mou.DynamicFileField(null=True, upload_to=coldfront.core.utils.mou.upload_to_func),
        ),
    ]
