# Generated by Django 3.2.5 on 2023-05-25 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20230524_0136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestFileModel',
        ),
    ]
