# Generated by Django 3.2.5 on 2023-05-25 17:20

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_delete_testfilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savioprojectallocationrequest',
            name='mou_file',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='mou/new_project_requests/'),
        ),
    ]
