# Generated by Django 5.2.12 on 2026-04-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_alter_historicalproject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectuser',
            options={'permissions': [('can_view_project_memberships', 'Can view project memberships via API')], 'verbose_name_plural': 'Project User Status'},
        ),
    ]
