# Generated by Django 3.2.5 on 2023-07-27 17:36

import coldfront.core.utils.mou
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_delete_testfilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savioprojectallocationrequest',
            name='mou_file',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(permissions=()), upload_to=coldfront.core.utils.mou.upload_to_func),
        ),
    ]
