# Generated by Django 5.2.14 on 2026-07-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_add_can_view_project_memberships_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuserremovalrequest',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
