# Generated by Django 3.2.5 on 2023-03-20 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('user', '0012_historicaluserprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaluserprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical user profile', 'verbose_name_plural': 'historical user profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='departments',
            field=models.ManyToManyField(through='department.UserDepartment', to='department.Department'),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.CreateModel(
            name='HistoricalUserDepartment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_authoritative', models.BooleanField(default=False)),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='department.department')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='user.historicaluserprofile')),
                ('user_profile', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.userprofile')),
            ],
            options={
                'verbose_name': 'HistoricalUserDepartment',
            },
        ),
    ]
