# Generated by Django 3.2.5 on 2023-05-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_historicaluserprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaluserprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical user profile', 'verbose_name_plural': 'historical user profiles'},
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
