# Generated by Django 3.2.5 on 2025-06-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_historicaluserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
