# Generated by Django 3.2.5 on 2023-03-16 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_add_user_departments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluserdepartment',
            old_name='userprofile',
            new_name='user_profile',
        ),
    ]
