# Generated by Django 3.2.5 on 2022-08-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_userprofile_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
