# Generated by Django 3.2.5 on 2023-09-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_description_and_is_valid_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbillingactivity',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Billing Activity', 'verbose_name_plural': 'historical Billing Activities'},
        ),
        migrations.AlterModelOptions(
            name='historicalbillingproject',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Billing Project', 'verbose_name_plural': 'historical Billing Projects'},
        ),
        migrations.AlterField(
            model_name='historicalbillingactivity',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalbillingproject',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
