# Generated by Django 5.2.4 on 2025-07-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaluserdepartment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical user department', 'verbose_name_plural': 'historical user departments'},
        ),
        migrations.AlterField(
            model_name='historicaluserdepartment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
