# Generated by Django 3.2.5 on 2023-12-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0012_cluster_access_request_remove_host_user_and_billing_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='securedirrequest',
            name='department',
            field=models.TextField(null=True),
        ),
    ]
