# Generated by Django 3.2.5 on 2023-05-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0013_auto_20230524_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='securedirrequest',
            name='mou_file',
            field=models.FileField(null=True, upload_to='mou/secure_directory_requests/'),
        ),
    ]
