# Generated by Django 3.2.5 on 2023-12-13 20:40

import coldfront.core.utils.mou
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0013_securedirrequest_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationadditionrequest',
            name='mou_file',
            field=coldfront.core.utils.mou.DynamicFileField(null=True, upload_to=coldfront.core.utils.mou.upload_to_func),
        ),
        migrations.AddField(
            model_name='securedirrequest',
            name='mou_file',
            field=coldfront.core.utils.mou.DynamicFileField(null=True, upload_to=coldfront.core.utils.mou.upload_to_func),
        ),
    ]
