# Generated by Django 3.2.5 on 2023-05-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0014_securedirrequest_mou_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationadditionrequest',
            name='mou_file',
            field=models.FileField(null=True, upload_to='mou/service_unit_purchase_requests/'),
        ),
    ]
