# Generated by Django 3.2.5 on 2024-04-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0013_allocationrenewalrequest_renewal_survey_answers'),
        ('allocation', '0014_add_mou_file_to_requests'),
    ]

    operations = [
    ]
