# Generated by Django 3.2.5 on 2023-06-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0015_allocationadditionrequest_mou_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationadditionrequest',
            name='mou_file',
            field=models.FileField(null=True, upload_to='mou/service_units_purchase_requests/'),
        ),
    ]
