# Generated by Django 3.2.5 on 2023-05-25 17:20

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0015_allocationadditionrequest_mou_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationadditionrequest',
            name='mou_file',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='securedirrequest',
            name='mou_file',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='mou/secure_directory_requests/'),
        ),
    ]
