# Generated by Django 3.2.5 on 2023-07-27 17:36

import coldfront.core.utils.mou
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0016_alter_allocationadditionrequest_mou_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='securedirrequest',
            name='department',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='allocationadditionrequest',
            name='mou_file',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(permissions=()), upload_to=coldfront.core.utils.mou.upload_to_func),
        ),
        migrations.AlterField(
            model_name='securedirrequest',
            name='mou_file',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(permissions=()), upload_to=coldfront.core.utils.mou.upload_to_func),
        ),
    ]
