# Generated by Django 5.2.4 on 2025-08-28 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0018_alter_historicalallocation_options_and_more'),
        ('billing', '0003_alter_historicalbillingactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrenewalrequest',
            name='billing_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_renewal_request_billing_activity', to='billing.billingactivity'),
        ),
    ]
