# Generated by Django 3.2.5 on 2023-03-16 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_userprofile_historicaluserdepartment_user_profile'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluserdepartment',
            old_name='userprofile',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='userdepartment',
            old_name='userprofile',
            new_name='user_profile',
        ),
        migrations.AlterUniqueTogether(
            name='userdepartment',
            unique_together={('user_profile', 'department')},
        ),
    ]
