# Generated by Django 5.2.6 on 2026-03-04 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_alter_historicalproject_options_and_more'),
        ('statistics', '0002_projecttransaction_projectusertransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWaitHeatmap30d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField()),
                ('partition', models.CharField(max_length=50)),
                ('cpu_bucket', models.CharField(max_length=20)),
                ('p50_wait_seconds', models.DecimalField(decimal_places=2, help_text='Median wait time in seconds', max_digits=11)),
                ('sample_size', models.IntegerField(help_text='Number of jobs in this bucket')),
            ],
            options={
                'verbose_name': 'Job Wait Heatmap (30-day)',
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['startdate'], name='job_startdate_idx'),
        ),
        migrations.AddIndex(
            model_name='jobwaitheatmap30d',
            index=models.Index(fields=['generated_at'], name='heatmap_generated_at_idx'),
        ),
    ]
